### ISSUE TITLE
jwt expired not resolved

### ISSUE THREAD

**Issue by colinmccann** [encorelab/ckx#4] opened 2016-05-26 19:39 UTC
Usually when I encounter this issue, it is after I have eg closed my laptop with the servers still running, then opened up later to see the JWT expired issue. This time it just happened when I went for a coffee - computer still on.

Just to be clear: I see no groups, clearing cache resolves the issue

![screen shot 2016-05-26 at 3 32 33 pm](https://cloud.githubusercontent.com/assets/754840/15587593/f8b6dbee-2357-11e6-8d69-97cc317568d3.png)
<img width="788" alt="screen shot 2016-05-26 at 3 32 40 pm" src="https://cloud.githubusercontent.com/assets/754840/15587596/fb74ab68-2357-11e6-9514-51559c517c96.png">

**Comment by houshuang** [comment] 2016-05-29 17:47
Interesting, right now it only clears the cache on startup, so reconnecting would still have the issue. Anyway I need to look into handling reconnection and socket failure etc, which isn't yet fully built-in to the Horizon client, so this issue will be part of that.

**Comment by houshuang** [comment] 2016-05-29 18:19
Not quite sure how to handle disconnect. There are [onDisconnected and onSocketError handlers](http://horizon.io/api/horizon/#disconnect) on the Horizon object, but what to do in these cases? I experimented with just reloading the page, but that would of course lead to loosing the place (unless we had meaningful URLs containing the board ID and maybe user token etc). However, it's worse than that, because in development, the Horizon.js is served by the Horizon server, and so if it reloads while HZ is not running (I tested by halting the HZ server), the page goes blank because it cannot access the Horizon object...

The problem is that if it has to reconnect, it has to deal with the fact that data on the server might have changed. ...

**Comment by houshuang** [comment] 2016-05-29 18:20
OK, so it seems like this particular issue was [fixed](https://github.com/rethinkdb/horizon/commit/e01e8608f09efa0e1ac4334eb1d44dc762378d4d), so I've updated the version of Horizon in package.json, and that should fix the issue (let me know if it doesn't). There is still a deeper issue of reconnecting etc which we need to track.

**Closed as completed** 2016-05-29 18:21 UTC
